version: "3.9"

services:
  web:
    build: .
    depends_on:
     - db
     - dbviewer
  db:
    image: postgres:13-alpine
    ports:
      - "5432:80"
    environment:
      POSTGRES_DB: "postgr"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "testadmin"
    volumes:
      - .:/var/lib/postgresql/data
  
  dbviewer:
    image: adminer:latest
    ports:
      - "8080:80"

